### ISSUE TITLE
Issue when splitting json array

### ISSUE THREAD

**Issue by sc4ut** [spring-cloud-stream-app-starters/splitter#2]
Hi, 
I'm using the 

- Spring Cloud Dataflow Server locally (Version: 1.2.2-RELEASE) and the 
- Splitter from the spring repository (Version: 1.2.0-RELEASE), 
- MessageBroker is RabbitMQ. 

When splitting an Json Array, my output is splitted, but also all quotation marks are removed. 
So i tried to send your jsonstring from your example, with your exact expression and got the same problem. My stream is an http source, splitter processor and sink log. 
Like This: 

> "http --port=9090 | splitter --expression=#jsonPath(payload,'$.store.book') | log"

Now just send your jsonstring via a Restclient to the port 9090 but got this output:

> 2017-08-22 09:50:43.881  INFO 11632 --- [litter.stream-1] log-sink                                 : {category=reference, author=Nigel Rees, title=Sayings of the Century, price=8.95}
> 2017-08-22 09:50:43.894  INFO 11632 --- [litter.stream-1] log-sink                                 : {category=fiction, author=Evelyn Waugh, title=Sword of Honour, price=12.99}
> 2017-08-22 09:50:43.895  INFO 11632 --- [litter.stream-1] log-sink                                 : {category=fiction, author=Herman Melville, title=Moby Dick, isbn=0-553-21311-3, price=8.99}
> 2017-08-22 09:50:43.896  INFO 11632 --- [litter.stream-1] log-sink                                 : {category=fiction, author=J. R. R. Tolkien, title=The Lord of the Rings, isbn=0-395-19395-8, price=22.99}

If now send to an mongodb sink e.g., it wont work. Is this a well known problem, or am I the only one? Maybe I just did something wrong?

**Comment by artembilan** [comment]
The `#jsonPath()` returns a `Map` of the sub-content in the original JSON.
Consider to use `--outputType=application/json` to make the Framework to convert that `Map` to the JSON before sending to the broker in between.

**Comment by sabbyanandan** [comment]
Hi, @sc4ut. In Spring Cloud Stream 2.0, we will _default_ to `application/json` as the content-type, so the explicit reference in the DSL won't be necessary. Until then, please use the `--outputType=application/json` to get around the described problem.

**Comment by sc4ut** [comment]
Thanks for your replies. It is working now. But only with an additional information:

The input payload need the header content-Type=application/json aswell. Otherwise the processor creates no output at all.
